import styled from "@emotion/styled";
import Head from "next/head";
import Image from "next/image";

const Thumbnail = styled.article`
  width: 348px;
  height: 466px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <section>
        <Thumbnail>
          \
          <Image src="#" alt="상품 이미지" />
        </Thumbnail>
        <article>정보</article>
      </section> */}
    </>
  );
}
